<?php

$GLOBALS['title'] = "Sean White & Associates - Website Terms & Conditions";
$GLOBALS['desc'] = "";
$GLOBALS['keywords'] = "terms and conditions, website terms";
include('header.php'); 
?>


  

      <section class="terms">
		<div class="container">

			<h1>Website Terms &amp; Conditions</h1>
			<p class='section-paragraph'><strong>PLEASE READ THESE TERMS AND CONDITIONS OF USE CAREFULLY. BY USING THIS Website, YOU AGREE TO THESE TERMS AND CONDITIONS.</strong></p>

			<p class='section-paragraph'>Services may not be available in all states so please call or check our website for details. Sean White & Associate’s services are not available in South Carolina.</p>

			<p class='section-paragraph'>Your access to and use of this Website is subject to the following terms and conditions of use (Terms of Use) and all applicable laws. These Terms of Use apply exclusively to your access to, and use of, this Website known as www.seanwhiteassociates.com (Sean White & Associates Website) which is exclusively owned and operated by Sean White & Associates, LLC (Sean White & Associates) and do not alter in any way the terms or conditions of any other agreement you may have with Sean White & Associates for services or otherwise. These Terms of Use may be changed by Sean White & Associates at any time in its sole discretion by posting the changes made to these Terms of Use, as revised, on this Website. Your use of this Website following the posting of such changes to the revised Terms of Use shall constitute your acceptance of any such changes. If you do not agree to these Terms of Use, our Privacy Statement, Sean White & Associates Service Agreement, or any other policy governing your access to or use of our Website you should immediately terminate your access to and use of the Website. If you have any question regarding these terms or your access to or use of this Website, please contact Customer Service at <a href="mailto:info@seanwhiteassociates.com">info@seanwhiteassociates.com</a>.</p>
			<h3 class='section-heading'>PRIVACY</h3>
			<p class='section-paragraph'>We respect the privacy of our customers and encourage you to read our <a href="./privacy-policy.php">Privacy Statement</a> so that you may make an informed decision about using our Website. There is important information regarding you’re the use and collection of your personal information in our Privacy Policy that we ask you to review.</p>
			<h3 class='section-heading'>COPYRIGHT</h3>
			<p class='section-paragraph'>Unless otherwise indicated, all Website materials, including, without limitation, the Sean White & Associates logo, and all designs, text, graphics, other files, and the selection and arrangement thereof are the proprietary and copyrighted property of Sean White & Associates or its licensors. You may electronically copy and print to a hard copy portions of this Website for the sole purpose of using materials it contains for informational and non-commercial, personal use only. Any other use of the materials in this Website including any commercial use, reproduction for purposes other than described herein, modification, distribution, republication, display or performance without the prior written permission of Sean White & Associates is strictly prohibited.</p>
			<h3 class='section-heading'>ACCESS TO SERVICES</h3>
			<p class='section-paragraph'>The Sean White & Associates Website allows you to create a unique user name and password to utilize many of our customized online services. Only individuals authorized by you, who over the age of 18, may access and use our Online Services. You may not access the Online Services from outside the country for which it was issued. Your unique user name may be restricted from accessing certain Materials otherwise available in the Online Services. Materials and features may be added to or withdrawn from the Online Services or otherwise changed without notice and in our sole discretion.</p>
			<h3 class='section-heading'>TRADEMARKS</h3>
			<p class='section-paragraph'>The Sean White & Associates, LLC logo, the Sean White & Associates Logo and any proprietary Service or service names contained in this Website are either trademarks or registered trademarks of Sean White & Associates or its licensors, and may not be copied, imitated or used, in whole or in part, without the prior written permission of Sean White & Associates. In addition, all page headers, custom graphics, button icons and scripts are service marks, trademarks and/or trade dress of Sean White & Associates, and may not be copied, imitated or used, in whole or in part, without the prior written permission of Sean White & Associates. All other trademarks, registered trademarks, Service names and company names or logos mentioned herein are the property of their respective owners.</p>
			<h3 class='section-heading'>UPLOADED CONTENT</h3>
			<p class='section-paragraph'>You agree that the content you upload in your personal space belongs to you and is for your personal use. You certify that you own and are responsible for any of the contents uploaded in your personal area and that you are not uploading and storing items that would infringe U.S. Copyright laws. You understand that you may not upload, post, reproduce or distribute in any way material protected by copyright, trademark, trade secret or other proprietary rights or which would violate any right of publicity, right of privacy or other right of any third party without first obtaining permission of the owner of such right.</p>
			<h3 class='section-heading'>SUBMISSIONS</h3>
			<p class='section-paragraph'>You agree that any materials, including but not limited to questions, comments, credit bureaus, credit reports, communications from credit reporting agencies, communications from credit bureaus, communications with credit reporting agencies, Communications with credit bureaus, communications with creditor(s), suggestions, ideas, plans, notes, drawings, original or creative materials or other information, provided by you in the form of e-mail or submissions to the Sean White & Associates Website, or postings on this Website, are not confidential and that Sean White & Associates shall have a perpetual, worldwide, non-exclusive license to use such materials as it deems appropriate.</p>
			<h3 class='section-heading'>SERVICES DESCRIPTION</h3>
			<p class='section-paragraph'>Sean White & Associates and its affiliates attempt to describe its Services as accurately as possible. However, Sean White & Associates does not warrant that Service descriptions or other content on this Website is accurate, complete, reliable, current, or error-free. If a Service offered by Sean White & Associates itself is not as described, your sole remedy is to cancel the service in the manner set forth in the Sean White & Associates Service Agreement. The prices displayed on the Website are in U.S. Dollars and are valid and effective only in the United States.</p>
			<h3 class='section-heading'>TERMS AND CONDITIONS OF THE USE OF THE Sean White & Associates CREDIT RESTORATION SERVICES:</h3>
			<p class='section-paragraph'>All use and/or purchase of Sean White & Associates's Credit Restoration services are subject to Sean White & Associates Service Agreement. Users can cancel their accounts at anytime, subject to the terms and conditions contained in the Sean White & Associates Service Agreement, however, since we are not able to pro-rate, the account will remain active until the end of the paid monthly cycle. There are no pro-rated refunds. Once your account is cancelled your member access to the site will be revoked upon the expiration of the paid monthly cycle. All cancellation shall also be strictly subject to the terms and conditions of the Sean White & Associates Service Agreement. In the event of a conflict between the terms and condition contained in this Terms of Use and the Sean White & Associates Services Agreement, the Sean White & Associates Services Agreement shall prevail and be deemed the governing document.</p>
			<h3 class='section-heading'>YOU ARE RESPONSIBLE FOR YOUR FINANCIAL DECISIONS</h3>
			<p class='section-paragraph'>We may share, transfer or provide your information as indicated in our Privacy Policy. Based on your consent, you may be contacted by third-party service providers, such as financial institutions, debt settlement companies, lenders and other financial professionals (“Providers”). We do not endorse or recommend the products or services of any Service Provider, and are not an agent or advisor to you or any Provider. We do not validate or investigate the licensing, certification or other requirements and qualifications of Service Providers. It is your responsibility to investigate Service Providers. You acknowledge and agree that Providers are solely responsible for any services that they may provide to you and that we are not liable for any losses, costs, damages or claims in connection with, arising from, or related to, your use of a Provider’s products or services. We urge you to obtain the advice of qualified professionals who are fully aware of your individual circumstances before you make any financial decisions. You acknowledge and agree that you rely on your own judgment and that of such advisors in selecting any products or services offered by Providers.</p>
			<h3 class='section-heading'>INAPPROPRIATE IMAGES OR WORDS</h3>
			<p class='section-paragraph'>Sean White & Associates reserves the right to remove any text or images uploaded by you that it deems in its sole judgment to be inappropriate or which it believes may subject it to any liability, including without limitation the following:</p>
			<ul>
				<li class="section-paragraph">images, text or other materials submitted by users that are protected by trademark, copyright, right
					of publicity or other proprietary right, without the express permission of the owner of those
					rights;
				</li>
				<li class="section-paragraph">profanity or offensive comments including but not limited to expressions of racism, bigotry or
					hatred, or that are abusive, slanderous or offensive;
				</li>
				<li class="section-paragraph">any illegal material such as expressions of abuse, offensive language and imagery, obscenity or any
					other material that could give rise to any civil or criminal liability under, or otherwise violate,
					any applicable law.
				</li>
			</ul>
			
			<h3 class='section-heading'>CLAIMS OF COPYRIGHT INFRINGEMENT; DESIGNATED AGENT</h3>
			<p class='section-paragraph'>If you believe that any material on this Website infringes upon any copyright that you own or control, or that any link on this Website directs users to another Website that contains material that infringes upon any copyright which you own or control, you may file a notification of such infringement to the email or address stated below.</p>
			<h3 class='section-heading'>ONLINE CONDUCT; REPEAT INFRINGER POLICY</h3>
			<p class='section-paragraph'>You agree to use Sean White & Associates Website only for lawful purposes. You are prohibited from posting on or transmitting through Sean White & Associates Website any unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, sexually explicit, profane, hateful, racially, ethnically or otherwise objectionable material of any kind that infringes the intellectual property rights or is otherwise injurious to third parties, including but not limited to any material that encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any applicable local, state, national or international law. Sean White & Associates may, at its discretion, terminate the accounts of any registered User who violate this policy.</p>
			<p class='section-paragraph'>Sean White & Associates respects the intellectual property of others, and we ask our Users to do the same. Sean White & Associates may, in appropriate circumstances and at its discretion, terminate the accounts of any User who infringe upon the intellectual property rights of others or who violate this policy.</p>
			<h3 class='section-heading'>CONTENT REVIEW</h3>
			<p class='section-paragraph'>Sean White & Associates may elect to electronically monitor areas of this Website and may disclose any content, records or electronic communication of any kind to satisfy any law, regulation or government request, if such disclosure is necessary or appropriate to operate this Website, or to protect the rights or property of Sean White & Associates, its independent contractors, service providers, consultants, sponsors, licensors or the public. Sean White & Associates retains the right, but not the obligation, to monitor and edit or remove any activity or content that it deems in its sole discretion to be harmful to its users, Sean White & Associates or the rights of any third party, or to violate any applicable law.</p>
			<h3 class='section-heading'>USE BY CHILDREN</h3>
			<p class='section-paragraph'>Sean White & Associates and the Sean White & Associates Website do not offer products and services for sale to children under 18. We sell products and services for purchase by adults only. By using this Website, you are representing to us that you are 18 years of age or older. Sean White & Associates will not be liable for any damages that may result from misrepresentation of age by a user of our Website.</p>
			<h3 class='section-heading'>INDEMNITY</h3>
			<p class='section-paragraph'>You agree to defend, indemnify and hold harmless Sean White & Associates, its Managers, it employees, its independent contractors, service providers and consultants, and their respective directors, employees and agents, from and against any third party claim, damages, costs and expenses (including, but not limited to, reasonable attorneys fees) arising out of your use of the Sean White & Associates Website or the use of any photographs, images or materials you provide, including without limitation any actual or threatened suit, demand, or claim made against Sean White & Associates and/or its independent contractors, service providers, or consultants, that use of the photographs, images or material provided infringes, misappropriates or otherwise violates any copyright, trademark, right of publicity or other proprietary right of any third party. You agree to pay any judgment or reasonable settlement offer resulting from any such suit, demand or claim.</p>
			<h3 class='section-heading'>DISCLAIMER</h3>
			<p class='section-paragraph'>EXCEPT IF EXPLICITLY STATED IN WRITING OTHERWISE BY Sean White & Associates, THE PRODUCTS AND/OR MATERIALS AND/OR SERVICES CONTAINED AND SOLD ON THE Sean White & Associates Website ARE PROVIDED ON AN AS IS BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. Sean White & Associates AND THE Sean White & Associates WEBSITE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. Sean White & Associates AND THE Sean White & Associates WEBSITE DOES NOT REPRESENT OR WARRANT THAT ANY PRODUCTS AND/OR MATERIALS AND/OR SERVICES ON THE Sean White & Associates Website, INCLUDING WITHOUT LIMITATION ANY INFORMATION ABOUT Sean White & Associates AND THE Sean White & Associates WEBSITE PROVIDED BY THIRD PARTIES, ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE. Sean White & Associates DOES NOT REPRESENT OR WARRANT THAT THE Sean White & Associates WEBSITE OR ITS SERVER(S) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>

			<p class='section-paragraph'>Sean White & Associates reserves the right to change any and all content contained on the Sean White & Associates Website at any time without notice. Reference to any products, services, materials, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof by Sean White & Associates and/or the Sean White & Associates Website.</p>

			<p class='section-paragraph'>If you rely on the Sean White & Associates website and any materials available on it, you do so solely at your own risk.</p>
			<h3 class='section-heading'>LIMITATION OF LIABILITY</h3>
			<p class='section-paragraph'>IN NO EVENT SHALL Sean White & Associates OR ITS OFFICER(S), MANAGER(S), DIRECTOR(S),MEMBER(S) OR EMPLOYEE(S) BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR INABILITY TO USE THIS WEBSITE OR THE MATERIALS CONTAINED IN AND/OR SERVICES SOLD ON AND/OR PRODUCTS SOLD ON, OR ACCESSED THROUGH, THE Sean White & Associates WEBSITE, INCLUDING WITHOUT LIMITATION ANY DAMAGES CAUSED BY OR RESULTING FROM RELIANCE BY USER ON ANY INFORMATION OBTAINED FROM Sean White & Associates, OR THAT RESULTS FROM MISTAKES, OMMISSIONS, INTERRUPTIONS, DELETION OF FILES OR E-MAILS, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION OR ANY FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, ACTS OF TERRORISM, THEFT, DESTRUCTION, OR UNAUTHORIZED ACESS TO THE Sean White & Associates RECORDS, PROGRAMS OR SERVICES.</p>

			<p class='section-paragraph'>IN NO EVENT SHALL THE AGGREGATE LIABILITY OF Sean White & Associates (WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE WHETHER ACTIVE, PASSIVE OR IMPUTED), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY) ARISING OUT OF OR RELATING TO THE USE OF Sean White & Associates WEBSITE EXCEED ANY COMPENSATION YOU PAY, IF ANY, TO Sean White & Associates AND/OR THE Sean White & Associates WEBSITE FOR ACCESS TO OR USE OR FOR SERVICES SOLD ON AND/OR PRODUCTS SOLD ON THE Sean White & Associates WEBSITE.</p>
			<h3 class='section-heading'>LINKING TO OUR WEBSITE</h3>
			<p class='section-paragraph'>You are granted a limited non-exclusive right to create a hyperlink to the Sean White & Associates Website provided such link does not portray Sean White & Associates or any of its materials or products or services in a false, misleading, derogatory or otherwise defamatory manner. This limited right may be revoked at any time. You may not use, frame or utilize framing techniques to enclose any Sean White & Associates and/or Sean White & Associates trademark, logo or other proprietary information, including the images found on the Sean White & Associates Website, the content of any text or the layout/design of any page or form contained on a page without Sean White & Associates's express written consent. Furthermore, you may not use any meta tags or any other hidden text utilizing a Sean White & Associates and Sean White & Associates name, trademark or Service name without Sean White & Associates's express written consent. Except as noted above, you are not conveyed any right or license by implication, estoppel or otherwise in or under any patent, trademark, copyright or proprietary right of Sean White & Associates or any third party. Sean White & Associates makes no claim or representation regarding, and accepts no responsibility for, the quality, content, nature or reliability of Websites linking to the Sean White & Associates Website.</p>
			<h3 class='section-heading'>THIRD PARTY LINKS</h3>
			<p class='section-paragraph'>The Sean White & Associates Website may provide links to Web pages and content of third parties (Third Party Content) as a service to those interested in this information. Sean White & Associates does not monitor, nor does it have any control over, any Third Party Content. Sean White & Associates does not endorse or adopt any Third Party Content and can make no guarantee as to its accuracy or completeness. Sean White & Associates makes no representations or warranties of any kind regarding such Third Party Content, or any information contained therein, and undertakes no responsibility to update or review any Third Party Content. When leaving the Sean White & Associates Website, you should be aware that the Sean White & Associates Website's terms and policies no longer govern, and, therefore, you should review the applicable terms and policies, including privacy and data gathering practices, of that site. Users use these links and Third Party Content contained therein at their own risk.</p>
			<h3 class='section-heading'>SEVERABILITY AND NONWAIVER</h3>
			<p class='section-paragraph'>If any provision of these Terms of Use shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms of Use and shall not affect the validity and enforceability of any remaining provisions. The failure of Sean White & Associates to insist upon or enforce strict performance of any of the provisions of these Terms of Use or to exercise any rights or remedies under these Terms of Use will not be construed as a waiver or relinquishment to any extent of Sean White & Associates right to assert or rely upon any such provisions, rights, or remedies in that or any other instance; rather, the same will be and remain in full force and effect.</p>
			<h3 class='section-heading'>APPLICABLE LAW</h3>
			<p class='section-paragraph'>The internal laws of the State of New Jersey will govern and construe these Terms of Use without giving effect to any conflict of laws provisions to the contrary. By use of this Website, you irrevocably consent to the jurisdiction of the courts of the State of New Jersey and agree that all disputes with Sean White & Associates venue shall be in the state or federal courts located in the State of New Jersey. If you access the Website from outside the United States, you do so at your own risk and are responsible for compliance with the laws of your jurisdiction.</p>
			<h3 class='section-heading'>TERMINATION</h3>
			<p class='section-paragraph'>Notwithstanding anything to the contrary herein, Sean White & Associates reserves the right, without notice and in its sole discretion, to terminate your use of this Website and to block or prevent future access to and use of this Website.</p>
			<h3 class='section-heading'>MISCELLANEOUS</h3>
			<p class='section-paragraph'>These General Terms and Conditions of Use may be changed from time to time without notice by Sean White & Associates in its sole discretion. Continued use of the Sean White & Associates Website's Online Services following any change constitutes acceptance of the change.</p>
			<p class='section-paragraph'>Sean White & Associates may suspend or discontinue providing Online Services to you without notice and pursue any other remedy legally available to it if you fail to comply with any of your obligations hereunder.</p>

			<p class='section-paragraph'>Except as otherwise provided herein, all notices and other communications hereunder by Sean White & Associates shall be in writing or displayed electronically on the Sean White & Associates Website. Notices shall be deemed to have been properly given on the date deposited in the U.S. mails, if mailed; on the date Sean White & Associates transmitted it to you electronically to the email address you have provided us, if sent via electronic mail; on the date first made available, if displayed Sean White & Associates Website; or on the date received, if delivered in any other manner.</p>
			<p class='section-paragraph'>The failure of Sean White & Associates or any third party supplier of Materials to enforce any provision hereof shall not constitute or be construed as a waiver of such provision or of the right to enforce it at a later time.</p>
			<p class='section-paragraph'>Each third party supplier of Materials has the right to assert and enforce these provisions directly on its own behalf as a third party beneficiary.</p>
			<h3 class='section-heading'>90 Day Refund Policy</h3>
			<p class='section-paragraph'>The Sean White & Associates money-back guarantee will be strictly subject to you complying with the following terms and conditions. For more information regarding the in the guarantee, please see: <a href="./90day.php">https://seanwhiteassociates.com/90day.php</a>.</p>

			<h3 class='section-heading'>COMMUNICATIONS TO YOU</h3>
			<p class='section-paragraph'>You agree that Sean White & Associates may send electronic mail to you for the purpose of advising you of changes or additions to this Site, about any of Sean White & Associates Services or services, or for such other purpose(s) as Sean White & Associates deems appropriate. You also agree that Sean White & Associates may share your personal information with certain third parties. Please see our <a href="/privacy-policy.php">Privacy Policy</a> for more detail.</p>
			<h3 class='section-heading'>QUESTIONS AND CONTACT INFORMATION</h3>
			<p class='section-paragraph'>General questions or comments about Sean White & Associates Website may be directed to Sean White & Associates Website's Customer Service Department at <a href="mailto:info@seanwhiteassociates.com">info@seanwhiteassociates.com</a></p>
			<h3 class='section-heading'>ADDRESS OF RECORD</h3>
			<p class='section-paragraph'><strong>Sean White & Associates, LLC</strong><br/>
			30 N Gould St, <br>
            Sheridan,  <br>
            WY 82801,
			<p class='section-paragraph'>Questions regarding this statement should be directed to <a href="mailto:info@seanwhiteassociates.com">info@seanwhiteassociates.com</a></p>
		</div>
	</section>







    <?php include('footer.php'); ?>